In [8]:
#open

with open("vidu2.txt", 'w') as f:
     f.write("Xin chao moi nguoi\n")

with open("vidu2.txt", 'a') as f:
     f.write("Xin chao moi nguoi 2")

In [9]:
with open("vidu2.txt", 'r') as f:
     print(f.read())

Xin chao moi nguoi
Xin chao moi nguoi 2


In [11]:
with open("vidu2.txt", 'r') as f:
     list_data = f.readlines()
     i = 1
     for data in list_data:
         print(f"{i} : {data}")
         i += 1

1 : Xin chao moi nguoi

2 : Xin chao moi nguoi 2

3 : Xin chao moi nguoi 3

4 : Xin chao moi nguoi 4

5 : Xin chao moi nguoi 5

6 : Xin chao moi nguoi 6



In [12]:
import numpy as np

In [13]:
a = np.array([1, 2, 3, 4, 5, 6])

In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
a[1]

np.int64(2)

In [17]:
a[-1]

np.int64(6)

In [18]:
a[1: 4:]

array([2, 3, 4])

In [22]:
a = np.append(a, 0)

In [23]:
np.append(a, [7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  0,  7,  8,  9, 10])

In [24]:
b = np.zeros(4)

In [25]:
b

array([0., 0., 0., 0.])

In [31]:
print(a)

[1 2 3 4 5 6 0]


In [36]:
a = np.delete(a, 2)
print(a)

[1 2 5 6 0]


In [37]:
np.delete(a, np.arange(1, 3))

array([1, 6, 0])

In [43]:
a = a + 2

In [44]:
a

array([ 6,  8, 14, 16,  4])

In [46]:
a.sort()

In [47]:
print(a)

[ 4  6  8 14 16]


In [49]:
list_ = [1, 2, 3, 4, 6, 7]

list_.sort(reverse= True)

list_

[7, 6, 4, 3, 2, 1]

In [50]:
print(a)

[ 4  6  8 14 16]


In [51]:
a[::-1]

array([16, 14,  8,  6,  4])

In [ ]:
#count len min max 

In [56]:
arr_x = [0, 0.1, 0.2, 0.3, 0.4]

arr_y = arr_x

arr_y[-1] = 1000
print(arr_y)

arr_x

[0, 0.1, 0.2, 0.3, 1000]


[0, 0.1, 0.2, 0.3, 1000]

# Boolen indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr % 2 == 0)

print(arr[arr >= 3])


[False  True False  True False  True False  True False  True]
[ 3  4  5  6  7  8  9 10]


In [65]:
array_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

In [66]:
print(array_2d.shape)

(3, 3)


In [69]:
array_2d[1, 1]

np.int64(5)

In [71]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [72]:
D = A @ B

print(D)

[[19 22]
 [43 50]]


In [76]:
arr = np.array([10, 20, 30, 40])

np.std(arr)

np.float64(11.180339887498949)